### ISSUE TITLE
new users don't read the initial message fully

### ISSUE THREAD

**Issue by daveloyall** [hashbang/dotfiles#15]
<+sebboh> Do users ask for help writing scripts or finding files they lost or                                        
              that sort of thing?  Are there any newbies here?              [23:08]                                      
    <lrvick> users ask for stuff like that all the time                     [23:13]                                      
    <lrvick> if you know something someone asks, by all means help                                                       
    <lrvick> There are also a bunch of other rooms too if you /list                                                      
    <lrvick> for various things                                             [23:14]                                      
    <lrvick> A lot of people end up here that have never used a terminal                                                 
    <lrvick> and have no idea wtf is going on, like they are in the matrix                                               
    <lrvick> so you ocassionally get super noobs that just managed to figure out                                         
             how to paste a command and hit enter a few times                                                            
    <lrvick> Also for most people this is their first time using a terminal                                              
             multiplexer                                                    [23:15]                                      
    <lrvick> they have now idea how to detach or re-attach and constantly                                                
             exit/reconnect everything                                                                                   
    <lrvick> A lot of people don't yet understand the benefits of having your chat                                       
             etc centralized and always-on on a remote system and this is all                                            
             magic.                                                         [23:16]                                      
    <+sebboh> That's a good list of potential additions to the welcome message                                           
              and/or that echo message.                                         
    
    
    <lrvick> We do try to cover that in the terminal welcome message        [23:17]                                      
    <lrvick> sadly no one reads it                                                                                       
    <lrvick> they read just enough to hop over to this tab                                                               
    <lrvick> then get stuck                                                                                              
    <lrvick> and start typing ls exit quit grep                                                                          
    <lrvick> its amusing                                                                                                 
    <+sebboh> Great.  That's great.  We can catch a LOT of users by hiding the                                           
              secret key combo to leave that first screen firther down.  The emacs                                       
              tutorial does a great job of this.                            [23:18]

**Comment by AlissaSquared** [comment]
This is more of an /etc/ issue because it's in /etc/skel but, I'll work on it anyways.

**Comment by AlissaSquared** [comment]
Closed, like a boss. The file will not actually be deleted until shell-etc is updated, however.
