### ISSUE TITLE
Configure nix/node/ruby/python/go/lua pkg managers to install to $HOME

### ISSUE THREAD

**Issue by lrvick** [hashbang/dotfiles#20]
- [ ] nix
- [x] node
- [x] ruby
- [x] python
- [x] go
- [x] lua

**Comment by gmcclins** [comment]
as far as node is this what you are looking for 

`NPM_PACKAGES="$HOME/.npm-packages"`
`mkdir -p "$NPM_PACKAGES"`
`echo "prefix = $NPM_PACKAGES" >> ~/.npmrc`

and then configure path in zshrc/.bashrc:

# NPM packages in homedir
`NPM_PACKAGES="$HOME/.npm-packages"`

# Tell our environment about user-installed node tools
`PATH="$NPM_PACKAGES/bin:$PATH"`

# Unset manpath so we can inherit from /etc/manpath via the `manpath` command
`unset MANPATH`
`MANPATH="$NPM_PACKAGES/share/man:$(manpath)"`

> i'm not sure about the manpath stuff

# Tell Node about these packages
`NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"`

> Now when you do an npm install -g, NPM will install the libraries into ~/.npm-packages/lib/node_modules, and link executable tools into ~/.npm-packages/bin, which is in your PATH.

Credit: [source](http://stackoverflow.com/questions/10081293)

**Comment by ChickenNuggers** [comment]
LuaRocks installs to `~/.luarocks` and I'm working on a `/etc/profile.d` patch to make Lua automatically support this.

Also, shouldn't we try doing this in `shell-etc` to make it system configuration instead of dotfiles? This is what caused the problem with Mutt previously.

**Comment by daurnimator** [comment]
> LuaRocks installs to ~/.luarocks and I'm working on a /etc/profile.d patch to make Lua automatically support this.

Merged via https://github.com/hashbang/shell-etc/pull/78

> Also, shouldn't we try doing this in shell-etc to make it system configuration instead of dotfiles? This is what caused the problem with Mutt previously.

Yep. this will allow users to override in their own dotfiles.

**Comment by ChickenNuggers** [comment]
Unfortunately by default either you have to install `npm` packages as a pseudo-global package; just running `npm install` downloads the package and places it in the current directory - this is nice, but not when it comes to per-user libraries and applications. I'm going to work on getting @gmcclins's setup working on a dev server before I approve it for here.

**Comment by ChickenNuggers** [comment]
So we tested on the shell servers last night and it looks like Ruby is configured to do this automatically. \o/ @hashbang/operators please double check (just install something with gem) so we can cross that off.

**Comment by ChickenNuggers** [comment]
@hashbang/administrators can someone install libruby-dev and check the above?

**Comment by KellerFuchs** [comment]
@ChickenNuggers Not entirely sure why you needed someone else to test it for you, but:
```
kellertest@da1:~$ gem install lolcat
Fetching: paint-1.0.1.gem (100%)
Successfully installed paint-1.0.1
Fetching: trollop-2.1.2.gem (100%)
Successfully installed trollop-2.1.2
Fetching: lolcat-42.1.43.gem (100%)
Successfully installed lolcat-42.1.43
Parsing documentation for lolcat-42.1.43
Installing ri documentation for lolcat-42.1.43
Parsing documentation for paint-1.0.1
Installing ri documentation for paint-1.0.1
Parsing documentation for trollop-2.1.2
Installing ri documentation for trollop-2.1.2
Done installing documentation for lolcat, paint, trollop after 1 seconds
3 gems installed

kellertest@da1:~$ ls -Al `which lolcat`
-rwx------ 1 kellertest kellertest 492 Oct 29 01:39 /home/kellertest/.gem/bin/lolcat
```

**Comment by ChickenNuggers** [comment]
Well I finally found where the `.gem/bin` was added due to something unrelated (Debian sucks, Node sucks, JavaScript sucks, burn it all) and wasn't sure if I set it or not. Adding to done list.

**Comment by ChickenNuggers** [comment]
node will be fixed with [#114](https://github.com/hashbang/shell-etc/pulls/144)

**Comment by ChickenNuggers** [comment]
go will be fixed with [#115](https://github.com/hashbang/shell-etc/pulls/115)

**Comment by ChickenNuggers** [comment]
nix should be fixed with [#116](https://github.com/hashbang/shell-etc/issues/116)

**Comment by ChickenNuggers** [comment]
python should be fixed with [#117](https://github.com/hashbang/shell-etc/pull/117)

**Comment by RyanSquared** [comment]
waiting on hashbang/shell-etc#136 for Node. might do Nix later.

**Comment by RyanSquared** [comment]
Closing. This exists in `/etc/profile.d`
