### ISSUE TITLE
Unable to verify signature

### ISSUE THREAD

**Issue by guilhermeasg** [hashbang/dotfiles#48]
Just created an account with you guys, it's amazing! Thanks for putting this together. :)

One problem I've found is that, for every login shell I spawn, cloning this repo fails at the signature checking stage. After manually checking out the repo to `.dotfiles` (because `dotfiles.sh` deletes it on failure):

```sh
gsg@da1:~/.dotfiles$ git verify-commit HEAD
gpg: keybox '/tmp/gpg.fXiPiG/pubring.kbx' created
gpg: Signature made Sun Jun 10 20:32:53 2018 UTC
gpg:                using RSA key 67553FBDA46BB71ABD2E0B0B8E47A1EC35A1551D
gpg: Good signature from "Lance R. Vick (Personal) <lance@lrvick.net>" [expired]
gpg:                 aka "Lance R. Vick (Work) <lance@bitgo.com>" [expired]
gpg:                 aka "[jpeg image of size 6119]" [expired]
gpg: WARNING: Using untrusted key!
gsg@da1:~/.dotfiles$ git log -1
commit 58b4119832b64ce7cb7e91a6501f4bc246084e49
Author: Lance R. Vick <lance@lrvick.net>
Date:   Sun Jun 10 13:32:52 2018 -0700

    fix tmux config for 2.1+ by making deprecated/ignored options quiet
gsg@da1:~/.dotfiles$ date
```

It looks like it's been signed with an expired key.

**Comment by guilhermeasg** [comment]
Just found about #38, closing this this to unify the discussion there.

**Comment by guilhermeasg** [comment]
Sorry for the noise. It actually looks like a separate issue, as GitHub shows 58b4119832b64ce7cb7e91a6501f4bc246084e49 as being verified, but `gpg` complains the associated key is untrusted.

**Comment by benharri** [comment]
Looks like his key expires today. I'll ping him.

**Comment by RyanSquared** [comment]
Pushed an empty signed commit.

**Comment by benharri** [comment]
@guilhermeasg can you repro? It *should* be fixed.

**Comment by guilhermeasg** [comment]
Yep, it's gone now. Thanks for the prompt resolution!
