### ISSUE TITLE
Remove dark blue from the default weechat config?

### ISSUE THREAD

**Issue by dpflug** [hashbang/dotfiles#6]
Might be a good idea, since so many people use dark backgrounds by default.

**Comment by AlissaSquared** [comment]
I've actually been debating replacing most of the dotfiles with my already-customized and much better (imo) version. I'll clean it up a bit to make it look better later and see if I can figure out how to make a pull request

**Comment by AlissaSquared** [comment]
Done, in reference to above comment.
#! will offer support on setting up a 256-color terminal or changing settings.
